version: "3.9"

services:
  lumen-estore:
    build:
      context: ./docker/lumen
      dockerfile: Dockerfile
    image: test-microservice-lumen
    container_name: ${CONTAINER_NAME_LUMEN_ESTORE}
    ports:
      - ${PORT_LUMEN_ESTORE}:8080
    volumes:
      - ./lumen-e-store:/src
    depends_on:
      - db
      - php-fpm
    dns:
      - 8.8.8.8
    networks:
      - lumen-net
  
  lumen-sales:
    build:
      context: ./docker/lumen
      dockerfile: Dockerfile
    image: test-microservice-lumen
    container_name: ${CONTAINER_NAME_LUMEN_SALES}
    ports:
      - ${PORT_LUMEN_SALES}:8080
    volumes:
      - ./lumen-sales:/src
    depends_on:
      - db
      - lumen-estore
    dns:
      - 8.8.8.8
    networks:
      - lumen-net

  lumen-warehouse:
    build:
      context: ./docker/lumen
      dockerfile: Dockerfile
    image: test-microservice-lumen
    container_name: ${CONTAINER_NAME_LUMEN_WAREHOUSE}
    ports:
      - ${PORT_LUMEN_WAREHOUSE}:8080
    volumes:
      - ./lumen-warehouse:/src
    depends_on:
      - db
      - lumen-sales
    dns:
      - 8.8.8.8
    networks:
      - lumen-net

  php-fpm:
    image: php-fpm-vue
    build: 
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ./laravel-producers:/var/www
    depends_on:
      - db
      - rabbitmq
    dns:
      - 8.8.8.8
    networks:
      - lumen-net

  nginx:
    image: nginx:alpine
    container_name: nginx-laravel
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./laravel-producers:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - db
      - rabbitmq
      - php-fpm
    networks:
      - lumen-net

  db:
    image: mysql:8.0.30
    container_name: db-mysql-laravel
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    # volumes:
    #   - ${MYSQL_DATA_PATH}:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - lumen-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${CONTAINER_NAME_RABBITMQ}
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - lumen-net
    
  # composer-laravel:
  #   image: composer:latest
  #   container_name: composer-laravel-rabbitmq
  #   volumes:
  #     - ./laravel-producers:/app
  #   command: >
  #     sh -c "composer update && composer install
  #           "
  #   networks:
  #     - lumen-net
    
networks:
  lumen-net:
    driver: bridge